### ISSUE TITLE
Missing package product

### ISSUE THREAD

**Issue by mathieut** [eonist/HybridCamera#52]
I am seeing the following errors when I open the project and try to compile it. Does anybody know how to fix them? 
Thank you!

<img width="263" alt="Screen Shot 2021-08-19 at 11 17 59" src="https://user-images.githubusercontent.com/41958/130123150-e0c82ac8-c72a-4ae3-8882-b562d78bf446.png">

**Comment by eonist** [comment]
Try to download the repo. Then open the Xcode project. Here is from testing just now in Xcode 12.5.1

<img width="1122" alt="Screenshot 2021-08-20 at 00 35 50" src="https://user-images.githubusercontent.com/11816788/130153172-a0c2a245-36de-4a59-943a-9232a68c98cc.png">

**Comment by mathieut** [comment]
Thanks for the quick response. I did re-download it and it is showing the same issue. Also on Xcode Version 12.5.1 (12E507).

**Comment by eonist** [comment]
A suggestion: There might be two ways of opening the xcode project. try to open the .xcodeproj file, rather than draging the entire folder onto xcode. which would open the package build, and could cause such errors. 

Other than that. XCode needs to download external deps. Try to copy the url under packages in the app target. Then click the + button and paste in the package url. This might force xcode to download the packages. Or throw an error about why it doesnt work. 

Seems very strange. Im sure its a small hickup somewhere.

**Comment by mathieut** [comment]
It started to work now, without doing anything. Strange, but thank you so much for your very quick response! 

Before I close this, are you planning to maintain and continue to update this project in the future? :)

**Comment by eonist** [comment]
Definitely going to maintain it. Its very low maintenance as is. Will add new features if they are in demand / fit the project. thanks ✨
